### ISSUE TITLE
Bug Report --    flist = cp["formatters"]["keys"]   File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.7/configparser.py", line 958, in __getitem__     raise KeyError(key) KeyError: 'formatters'

### ISSUE THREAD

**Issue by monajalal** [pderoovere/dimo-labeling#1]
```
(dimo-labeling) mona@ada:~/dimo-labeling$ python backend/api.py --path test_dataset/
Traceback (most recent call last):
  File "backend/api.py", line 13, in <module>
    logging.config.fileConfig('logging.conf')
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.7/logging/config.py", line 71, in fileConfig
    formatters = _create_formatters(cp)
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.7/logging/config.py", line 104, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'

```

Ubuntu 22.04

**Comment by monajalal** [comment]
this bug does not happen on bop branch

```
(dimo-labeling) mona@DOS:~/dimo-labeling/backend$ python api.py --path test_dataset/
 * Serving Flask app 'api'
 * Debug mode: off
2024-03-21 23:38:41,120  INFO   WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:4321
 * Running on http://10.0.0.97:4321
2024-03-21 23:38:41,120  INFO   Press CTRL+C to quit
```

so I am going to close it
