### ISSUE TITLE
backend is requesting for scene_gt.json for annotation UI

### ISSUE THREAD

**Issue by monajalal** [pderoovere/dimo-labeling#6]
Hi Peter,

Thanks a lot for pushing the new changes.

I followed these instructions:

```
(dimo-labeling) mona@ada:~/dimo-labeling/backend$ python api.py --path ../test_data/ --models_dir ../test_data/models/ --images_dir ../test_data/real_camera/  
 * Serving Flask app 'api'
 * Debug mode: off
Address already in use
Port 4321 is in use by another program. Either identify and stop that program, or start the server with a different port.
(dimo-labeling) mona@ada:~/dimo-labeling/backend$ python api.py --path ../test_data/ --models_dir ../test_data/models/ --images_dir ../test_data/real_camera/  
 * Serving Flask app 'api'
 * Debug mode: off
2024-04-01 14:17:11,143  INFO   WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:4321
 * Running on http://172.16.152.25:4321
2024-04-01 14:17:11,143  INFO   Press CTRL+C to quit
2024-04-01 14:21:27,037  ERROR  Exception on /load [POST]
Traceback (most recent call last):
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "api.py", line 34, in load
    dataset = ds_loader.load(_path, _args)
  File "/home/mona/dimo-labeling/backend/dataset_loader.py", line 17, in load
    scenes = self.load_scenes(parts, path, path / args.images_dir, args.mode)
  File "/home/mona/dimo-labeling/backend/dataset_loader.py", line 42, in load_scenes
    return [
  File "/home/mona/dimo-labeling/backend/dataset_loader.py", line 43, in <listcomp>
    self.load_scene(parts, main_path, scene_path, mode)
  File "/home/mona/dimo-labeling/backend/dataset_loader.py", line 49, in load_scene
    with open(path / "scene_gt.json") as f_gt, open(
FileNotFoundError: [Errno 2] No such file or directory: '../test_data/../test_data/real_camera/000000/scene_gt.json'
2024-04-01 14:21:27,038  INFO   127.0.0.1 - - [01/Apr/2024 14:21:27] "POST /load HTTP/1.1" 500 -
2024-04-01 14:21:32,020  ERROR  Exception on /load [POST]
Traceback (most recent call last):
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "api.py", line 34, in load
    dataset = ds_loader.load(_path, _args)
  File "/home/mona/dimo-labeling/backend/dataset_loader.py", line 17, in load
    scenes = self.load_scenes(parts, path, path / args.images_dir, args.mode)
  File "/home/mona/dimo-labeling/backend/dataset_loader.py", line 42, in load_scenes
    return [
  File "/home/mona/dimo-labeling/backend/dataset_loader.py", line 43, in <listcomp>
    self.load_scene(parts, main_path, scene_path, mode)
  File "/home/mona/dimo-labeling/backend/dataset_loader.py", line 49, in load_scene
    with open(path / "scene_gt.json") as f_gt, open(
FileNotFoundError: [Errno 2] No such file or directory: '../test_data/../test_data/real_camera/000000/scene_gt.json'
2024-04-01 14:21:32,021  INFO   127.0.0.1 - - [01/Apr/2024 14:21:32] "POST /load HTTP/1.1" 500 -
2024-04-01 14:21:46,422  ERROR  Exception on /load [POST]
Traceback (most recent call last):
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "api.py", line 34, in load
    dataset = ds_loader.load(_path, _args)
  File "/home/mona/dimo-labeling/backend/dataset_loader.py", line 17, in load
    scenes = self.load_scenes(parts, path, path / args.images_dir, args.mode)
  File "/home/mona/dimo-labeling/backend/dataset_loader.py", line 42, in load_scenes
    return [
  File "/home/mona/dimo-labeling/backend/dataset_loader.py", line 43, in <listcomp>
    self.load_scene(parts, main_path, scene_path, mode)
  File "/home/mona/dimo-labeling/backend/dataset_loader.py", line 49, in load_scene
    with open(path / "scene_gt.json") as f_gt, open(
FileNotFoundError: [Errno 2] No such file or directory: '../test_data/../test_data/real_camera/000000/scene_gt.json'
2024-04-01 14:21:46,422  INFO   127.0.0.1 - - [01/Apr/2024 14:21:46] "POST /load HTTP/1.1" 500 -

```

and

```
(dimo-labeling) mona@ada:~/dimo-labeling$ cd frontend/
(dimo-labeling) mona@ada:~/dimo-labeling/frontend$ nvm use
Found '/home/mona/dimo-labeling/frontend/.nvmrc' with version <20.12.0>
N/A: version "v20.12.0" is not yet installed.

You need to run `nvm install` to install and use the node version specified in `.nvmrc`.
(dimo-labeling) mona@ada:~/dimo-labeling/frontend$ nvm install 
Found '/home/mona/dimo-labeling/frontend/.nvmrc' with version <20.12.0>
Downloading and installing node v20.12.0...
Downloading https://nodejs.org/dist/v20.12.0/node-v20.12.0-linux-x64.tar.xz...
##################################################################################################################################################################################################### 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v20.12.0 (npm v10.5.0)
(dimo-labeling) mona@ada:~/dimo-labeling/frontend$ npm install --save-dev
npm WARN deprecated model@0.0.6: model is no longer maintained.

added 978 packages, and audited 979 packages in 17s

117 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
(dimo-labeling) mona@ada:~/dimo-labeling/frontend$ ng serve 
Workspace extension with invalid name (defaultProject) found.
? Would you like to share pseudonymous usage data about this project with the Angular Team
at Google under Google's Privacy Policy at https://policies.google.com/privacy. For more
details and how to change this setting, see https://angular.io/analytics. Yes

Thank you for sharing pseudonymous usage data. Should you change your mind, the following
command will disable this feature entirely:

    ng analytics disable

Global setting: enabled
Local setting: enabled
Effective status: enabled
Option "browserTarget" is deprecated: Use 'buildTarget' instead.
⠋ Generating browser application bundles (phase: setup)...    TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022" and "false" respectively by the Angular CLI. To control ECMA version and features use the Browserslist configuration. For more information, see https://angular.io/guide/build#configuring-browser-compatibility
    NOTE: You can set the "target" to "ES2022" in the project's tsconfig to remove this warning.
✔ Browser application bundle generation complete.

Initial chunk files   | Names         |  Raw size
vendor.js             | vendor        |   6.66 MB | 
styles.css, styles.js | styles        | 400.05 kB | 
polyfills.js          | polyfills     | 336.44 kB | 
main.js               | main          | 154.76 kB | 
scripts.js            | scripts       |  32.99 kB | 
runtime.js            | runtime       |   6.51 kB | 

                      | Initial total |   7.57 MB

Build at: 2024-04-01T18:21:12.771Z - Hash: cda45b9ddd712f44 - Time: 12362ms

Warning: /home/mona/dimo-labeling/frontend/src/app/image-render-overlay/image-render-overlay.component.ts depends on 'panzoom'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies



** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


✔ Compiled successfully.



```

However, I don't understand why you need the scene_gt.json ? We are trying to create a ground truth so we shouldn't need this, right?

Also, here is the structure of my test dataset, could you please share a minimal `tree .` for your data structure that you are trying to create the groundtruth for?

```
(base) mona@ada:~/dimo-labeling/test_data$ tree .
.
├── models
│   ├── models_info.json
│   └── obj_000001.ply
└── real_camera
    ├── 000000
    │   └── rgb
    │       ├── 000000.png
    │       ├── 000001.png
    │       ├── 000002.png
    │       └── 000003.png
    └── 000001
        └── rgb
            ├── 000000.png
            ├── 000001.png
            ├── 000002.png
            └── 000003.png

6 directories, 10 files
```

When I look at the `scene_gt.json` for `lm` dataset, it basically contains the ground truth which we are technically trying to create with your UI, am I right?

----------------------------------------

Also, here's my angular setup details

```
(dimo-labeling) mona@ada:~/dimo-labeling/frontend$ ng version
Workspace extension with invalid name (defaultProject) found.

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.3.2
Node: 20.12.0
Package Manager: npm 10.5.0
OS: linux x64

Angular: 17.3.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.2
@angular-devkit/build-angular   17.3.2
@angular-devkit/core            17.3.2
@angular-devkit/schematics      17.3.2
@angular/cli                    17.3.2
@schematics/angular             17.3.2
rxjs                            7.8.1
typescript                      5.4.3
zone.js                         0.14.4

```

In your article, you also have mentioned

![image](https://github.com/pderoovere/dimo-labeling/assets/1892917/02ac2fd4-46cf-4c80-abe4-1bd0b603a9ff)

Also, if my understanding is wrong (which probably is), could you please guide how to create `scene_gt.json` for images I am capturing using Intel RealSense D435 camera?

**Comment by gachiemchiep** [comment]
@monajalal 

Here is an example of scene_gt.json and scene_camera.json

[scene_gt.json](https://github.com/pderoovere/dimo-labeling/files/14912502/scene_gt.json)
[scene_camera.json](https://github.com/pderoovere/dimo-labeling/files/14912504/scene_camera.json)

you can create by using this code

```bash
# scene_gt
data_path = "scene_gt.json"
for i in range(0, 82):
    data[str(i)] = list()
with open(data_path, "w") as fid:
    json.dump(data, fid, indent=2)

# scene_camera.json
data_path = "scene_camera.json"
for i in range(0, 82):
    item_data = dict();
    item_data["cam_K"] = [922.334106445312, 0.0, 637.2053833007816, 0.0, 922.389343261719, 367.810333251953, 0.0, 0.0, 1.0]
    item_data["depth_scale"] = 1.0
    item_data["cam_R_w2c"] = [1.0, 0, 0, 0, 1.0, 0, 0, 0, 1.0]
    item_data["cam_t_w2c"] = [0, 0, 0.0]
    scene_camera_data[str(i)] = item_data

with open(data_path, "w") as fid:
    json.dump(scene_camera_data, fid, indent=2)
```

**Comment by pderoovere** [comment]
Yes, `scene_gt_world.json` (poses relative to shared world frame) _or_ `scene_gt.json` (per-image poses relative to camera) should exist for the tool to work correctly. 
When starting from scenes without object labels, these files can contain empty lists. For example, `scene_gt_world.json` (in each scene folder) can just be `[]`.

**Comment by monajalal** [comment]
@gachiemchiep and @pderoovere 

Thank you both for your guidance,

I followed the code snippet from @gachiemchiep 
and 
I have

```
(base) mona@ada:~/dimo-labeling/test_data$ tree .
.
├── models
│   ├── models_info.json
│   └── obj_000001.ply
└── real_camera
    └── 000000
        ├── rgb
        │   ├── 000000.png
        │   ├── 000001.png
        │   ├── 000002.png
        │   └── 000003.png
        ├── scene_camera.json
        └── scene_gt.json

4 directories, 8 files
```

However, no image gets loaded into UI and I am also not getting error in either of backend or frontend.

Could you please help me with this?

![Screenshot from 2024-04-16 10-43-36](https://github.com/pderoovere/dimo-labeling/assets/1892917/8f2f5c28-f454-4b6c-85c9-e7eefa409e59)



```
mona@ada:~/dimo-labeling$ git log
commit 5a2f3f283d95fdd601b85679f8a3b7dd71a9ffde (HEAD -> main, origin/main, origin/HEAD)
Author: Peter De Roovere <peter.deroovere@robojob.eu>
Date:   Fri Apr 12 21:52:59 2024 +0200

    Fixed delete button not visible

```


Backend:

```
(dimo-labeling) mona@ada:~/dimo-labeling/backend$ python api.py --path ../test_data/ --models_dir ../test_data/models/ --images_dir ../test_data/real_camera/ 
 * Serving Flask app 'api'
 * Debug mode: off
2024-04-16 10:42:59,497  INFO   WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:4321
 * Running on http://172.16.152.25:4321
2024-04-16 10:42:59,497  INFO   Press CTRL+C to quit
2024-04-16 10:43:06,305  INFO   loading parts w.r.t camera
2024-04-16 10:43:06,306  INFO   127.0.0.1 - - [16/Apr/2024 10:43:06] "POST /load HTTP/1.1" 200 -
2024-04-16 10:43:06,618  INFO   127.0.0.1 - - [16/Apr/2024 10:43:06] "GET /test_data/real_camera/000000/rgb/000000.png HTTP/1.1" 404 -
2024-04-16 10:43:06,623  INFO   127.0.0.1 - - [16/Apr/2024 10:43:06] "GET /test_data/real_camera/000000/rgb/000000.png HTTP/1.1" 404 -

```

Frontend:

```
(dimo-labeling) mona@ada:~/dimo-labeling/frontend$ ng serve
Workspace extension with invalid name (defaultProject) found.
Option "browserTarget" is deprecated: Use 'buildTarget' instead.
⠋ Generating browser application bundles (phase: setup)...    TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022" and "false" respectively by the Angular CLI. To control ECMA version and features use the Browserslist configuration. For more information, see https://angular.io/guide/build#configuring-browser-compatibility
    NOTE: You can set the "target" to "ES2022" in the project's tsconfig to remove this warning.
✔ Browser application bundle generation complete.

Initial chunk files   | Names         |  Raw size
vendor.js             | vendor        |   6.66 MB | 
styles.css, styles.js | styles        | 400.14 kB | 
polyfills.js          | polyfills     | 336.44 kB | 
main.js               | main          | 154.76 kB | 
scripts.js            | scripts       |  32.99 kB | 
runtime.js            | runtime       |   6.51 kB | 

                      | Initial total |   7.57 MB

Build at: 2024-04-16T14:37:52.635Z - Hash: 9b5331b737c0b07d - Time: 4174ms

Warning: /home/mona/dimo-labeling/frontend/src/app/image-render-overlay/image-render-overlay.component.ts depends on 'panzoom'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies



** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


✔ Compiled successfully.



```

```
(base) mona@ada:~/dimo-labeling/test_data/models$ cat models_info.json 
{
  "1": {"diameter": 1503.815, "min_x": -487.5, "min_y": -570.0, "min_z": 0.0, "size_x": 975.0, "size_y": 1140.0, "size_z": 106.0}
 }
```

**Comment by pderoovere** [comment]
It looks like the images are not found (404). `--models_dir` and `--images_dir` should be relative to the dataset path (`--path`). So in your case:
```
python api.py --path ../test_data/ --models_dir models --images_dir real_camera
```

If this does not solve it, please provide your dataset (or a subset of it), so I can reproduce the problem.

**Comment by monajalal** [comment]
@pderoovere 

Thank you so much. The image got loaded but not the model after using `python api.py --path ../test_data/ --models_dir models --images_dir real_camera`

```
2024-04-17 15:59:53,649  ERROR  Exception on /pose [POST]
Traceback (most recent call last):
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mona/anaconda3/envs/dimo-labeling/lib/python3.8/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "api.py", line 52, in pose
    _pose = pose_calculator.calc_pose(
  File "/home/mona/dimo-labeling/backend/pose_calculator.py", line 12, in calc_pose
    _, rvecs, tvecs, _ = cv2.solvePnPRansac(
cv2.error: OpenCV(4.9.0) /io/opencv/modules/calib3d/src/solvepnp.cpp:227: error: (-215:Assertion failed) npoints >= 4 && npoints == std::max(ipoints.checkVector(2, CV_32F), ipoints.checkVector(2, CV_64F)) in function 'solvePnPRansac'

2024-04-17 15:59:53,650  INFO   127.0.0.1 - - [17/Apr/2024 15:59:53] "POST /pose HTTP/1.1" 500 -

```

I see this in left-hand pane

![image](https://github.com/pderoovere/dimo-labeling/assets/1892917/a5a7d1ef-88f7-48ee-95ca-73bc8a8d8fd3)


In case this may be important, here is the information on the image

```
(base) mona@ada:~/dimo-labeling/test_data/real_camera/000000/rgb$ exiftool 000000.png 
ExifTool Version Number         : 12.40
File Name                       : 000000.png
Directory                       : .
File Size                       : 444 KiB
File Modification Date/Time     : 2024:04:09 16:08:11-04:00
File Access Date/Time           : 2024:04:17 15:59:12-04:00
File Inode Change Date/Time     : 2024:04:16 10:41:17-04:00
File Permissions                : -rwxrwxrwx
File Type                       : PNG
File Type Extension             : png
MIME Type                       : image/png
Image Width                     : 640
Image Height                    : 480
Bit Depth                       : 8
Color Type                      : RGB
Compression                     : Deflate/Inflate
Filter                          : Adaptive
Interlace                       : Noninterlaced
Image Size                      : 640x480
Megapixels                      : 0.307
```

**Comment by pderoovere** [comment]
Please provide more information about your actions.
There are no object annotations, so you should click `+` to add a new part annotation?
The stacktrace indicates you tried to calculae a pose from correspondences?
